version: "3"
services:
  jobmanager:
    container_name: jobmanager
    image: flink:latest
    networks:
      - flink-network
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager


  taskmanager:
    container_name: taskmanager
    image: flink:latest
    networks:
      - flink-network
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

networks:
  flink-network:
    external: true